name: Manually deploy
on:
  repository_dispatch:
    types: [update_note]

# on: 
#   workflow_dispatch: # ここをrepository_dispatchから変更
#     inputs:
#       reason:
#         description: 'The reason for the manual run'     
#         required: true
#         default: 'No particular reason'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
      - name: Debug
        run: |
          echo "Bucket: ${{ secrets.AWS_S3_BUCKET }}"
          echo "CF ID: ${{ secrets.AWS_CF_ID }}"
          echo "Bucket: ${{ secrets.ACCESS_KEY_ID }}"
          echo "CF ID: ${{ secrets.SECRET_ACCESS_KEY }}"
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          echo "AWS s3 sync"
          aws s3 sync --region ap-northeast-1 ./out s3://${{ secrets.AWS_S3_BUCKET}} --delete
          echo "AWS CF reset"
          aws cloudfront create-invalidation --region ap-northeast-1 --distribution-id ${{ secrets.AWS_CF_ID }} --paths "/*"
